version: '3.7'

services:
  advent:
    build:
      context: ../
    entrypoint: /app/docker/entrypoint.sh
    container_name: "advent"
    volumes:
      - ../:/app
      - advent_bundle:/bundle
    env_file: ../.env
    environment:
      BUNDLE_PATH: /bundle
      BUNDLE_SILENCE_ROOT_WARNING: 1

  advent_bundle:
    image: busybox
    container_name: "advent_bundle"
    volumes:
      - advent_bundle:/bundle

volumes:
  advent_bundle:
