x-default-volumes: &default-volumes
  volumes:
    - ../:/advent
    - adventbundle:/advent/vendor/bundle

x-default-build-args: &default-build-args
  args:
    APPUID: ${APPUID}
    APPGID: ${APPGID}

volumes:
  adventbundle:

services:
  adventweb:
    container_name: 'adventweb'
    tty: true
    command: 'bin/dev'
    build:
      context: ../
      dockerfile: Dockerfile.web
      target: development
      << : *default-build-args
    << : *default-volumes
    env_file: ../.env
    tmpfs:
      - /tmp
